name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * *'

env:
  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  smoke-tests:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v3

      - &setup-node
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - &install-deps
        name: Install dependencies
        run: npm ci

      - &install-browsers
        name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Smoke Tests
        run: npx playwright test --grep "@smoke"
        env:
          CI: true

      - name: Upload Smoke Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-report
          path: playwright-report

  regression-tests:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-node
      - *install-deps
      - *install-browsers

      - name: Run Regression Tests
        run: npx playwright test --grep "@regression"
        env:
          CI: true

      - name: Upload Regression Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: regression-report
          path: playwright-report