name: Playwright Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      report-path: playwright-report
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Set report-path output
        id: set-report
        run: echo "report-path=playwright-report" >> $GITHUB_OUTPUT