name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  smoke-tests:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/playwright-setup.yml
    with:
      grep-filter: "@smoke"
      workers: 2
    secrets:
      BASE_URL: ${{ secrets.BASE_URL }}

  regression-tests:
    if: ${{ github.event_name == 'schedule' }}
    uses: ./.github/workflows/playwright-setup.yml
    with:
      grep-filter: "@regression"
      workers: 2
    secrets:
      BASE_URL: ${{ secrets.BASE_URL }}

  publish-allure:
    needs: [smoke-tests, regression-tests]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Allure HTML Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report-@regression
          path: docs/allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/allure-report