name: Playwright Tests

on:
  push:
    branches: [ master ]        # runs on pushes to master
  pull_request:
    branches: [ master ]        # runs on PRs targeting master
  schedule:
    - cron: '0 6 * * *'         # nightly at 00:00 CST (06:00 UTC)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1
        with:
          testCommand: npm test

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report