name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  smoke-tests:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/playwright-setup.yml
    with:
      grep-filter: "@smoke"
      workers: 2
    secrets:
      BASE_URL: ${{ secrets.BASE_URL }}

  regression-tests:
    if: ${{ github.event_name == 'schedule' }}
    uses: ./.github/workflows/playwright-setup.yml
    with:
      grep-filter: "@regression"
      workers: 2
    secrets:
      BASE_URL: ${{ secrets.BASE_URL }}

  publish-after-push:
    if: github.event_name == 'push'
    needs: smoke-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Smoke Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report-@smoke
          path: docs/allure-report

      - name: Deploy Smoke Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/allure-report

  publish-after-schedule:
    if: github.event_name == 'schedule'
    needs: regression-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Regression Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report-@regression
          path: docs/allure-report

      - name: Deploy Regression Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/allure-report