name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  smoke-tests:
    if: ${{ github.event_name != 'schedule' }}
    uses: ./.github/workflows/playwright-test.yml
    with:
      grep-filter: "@smoke"
    secrets:
      BASE_URL: ${{ secrets.BASE_URL }}

  regression-tests:
    if: ${{ github.event_name == 'schedule' }}
    uses: ./.github/workflows/playwright-test.yml
    with:
      grep-filter: "@regression"
    secrets:
      BASE_URL: ${{ secrets.BASE_URL }}